projeventos/appeventos/urls.py
from django.urls import path
#from .views import index,listar_eventos,listar_atividades,exibir_form_inscricao,registrar_inscricao,listar_participantes
from .views import EventoView,AtividadeView,AtividadeParticipanteView,InscricaoView,MinistranteListView,MinistranteCreateUpdateView,MinistranteDeleteView,ParticipanteCreateView,EventosLoginView,EventosLogoutView,AvalicaoCreateView,ToggleDarkModeView,FormContatoView,MinistranteFormCreateUpdateView
from django.views.generic import TemplateView
app_name='appeventos'
#urlpatterns=[
#    path('',index,name='index'),
#    path('eventos/listar',listar_eventos,name='listar_eventos'),
#    path('eventos/<int:evento_id>/atividades/listar',listar_atividades,name='listar_atividades'),
#    path('eventos/atividades/<int:atividade_id>/inscrever',exibir_form_inscricao,name='exibir_form_inscricao'),
#    path('eventos/atividades/<int:atividade_id>/registrar',registrar_inscricao,name="registrar_inscricao"),
#    path('eventos/atividades/<int:atividade_id>/participantes',listar_participantes,name='listar_participantes')
#]

urlpatterns=[
    path('',TemplateView.as_view(template_name='appeventos/index.html'),name='index'),
    path('eventos/listar',EventoView.as_view(),name='listar_eventos'),
    path('eventos/<int:evento_id>/atividades/listar',AtividadeView.as_view(),name='listar_atividades'),
    path('eventos/atividades/<int:atividade_id>/inscrever',InscricaoView.as_view(),name='exibir_form_inscricao'),
    path('eventos/atividades/<int:atividade_id>/registrar',InscricaoView.as_view(),name="registrar_inscricao"),
    path('eventos/atividades/<int:atividade_id>/participantes',AtividadeParticipanteView.as_view(),name='listar_participantes'),
    path('eventos/atividades/<int:atividade_id>/registrar_presenca',AtividadeParticipanteView.as_view(),name='registrar_presenca'),
    path('eventos/atividades/<int:atividade_id>/avaliar',AvalicaoCreateView.as_view(),name='avaliar_atividade'),
    path('ministrantes',MinistranteListView.as_view(),name='listar_ministrantes'),
    #path('ministrantes/cadastrar',MinistranteCreateUpdateView.as_view(),name='cadastrar_ministrante'),
    #path('ministrante/<int:ministrante_id>/editar',MinistranteCreateUpdateView.as_view(),name='editar_ministrante'),
    path('ministrantes/cadastrar',MinistranteFormCreateUpdateView.as_view(),name='cadastrar_ministrante'),
    path('ministrante/<int:ministrante_id>/editar',MinistranteFormCreateUpdateView.as_view(),name='editar_ministrante'),
    path('ministrante/<int:pk>/excluir',MinistranteDeleteView.as_view(),name='excluir_ministrante'),
    path('participantes/registrar',ParticipanteCreateView.as_view(),name='registrar_participante'),
    path('darkmode/',ToggleDarkModeView.as_view(),name='darkmode'),
    path('contato/',FormContatoView.as_view(),name='contato'),
    path('login/',EventosLoginView.as_view(),name='login'),
    path('logout/',EventosLogoutView.as_view(),name='logout'),
    ]

projeventos/projeventos/urls.py
from django.contrib import admin
from django.urls import path,include,reverse
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("appeventos/",include("appeventos.urls")),
     path("",RedirectView.as_view(url="appeventos/")),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projeventos/appeventos/models.py
# Create your models here.
from django.db import models
from django.db.models import Q,Count
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from datetime import timedelta

class Ministrante(models.Model):
    nome = models.CharField(max_length=150,verbose_name="Nome")
    data_nascimento = models.DateField(verbose_name="Data de Nascimento")
    link_curriculo = models.URLField(verbose_name="Link do Currículo")

    def __str__(self):
        return self.nome
    """
        Como estratégia de gerenciamento de erros, criamos um dicionário para reter as mensagens de erro por campo,
        de forma que o usuário receba as informações da forma correta e de uma única vez.
    """
    def clean(self):
        erros={} #Erros são gerados de uma única vez e gerada uma única vez.

        if len(self.nome.strip())<5:
            erros["nome"]="Nome não pode ter menos do que 5 caracteres"
            #raise ValidationError("Nome não pode ter menos do que 5 caracteres")
        
        if self.data_nascimento != None:
            if self.data_nascimento > timezone.now().date():
                erros["data_nascimento"]="Data de Nascimento não pode ser no futuro"
            dataref=timedelta(days=18*365.25)
            print(dataref)
            data_limite = timezone.now().date() - dataref
            print(data_limite)
            if self.data_nascimento > data_limite:
                erros['data_nascimento'] = "O ministrante deve ter, no mínimo, 18 anos de idade."

        url_validator=URLValidator()

        try:
            url_validator(self.link_curriculo)
        except ValidationError:
            erros["link_curriculo"]="O Link do currículo precisa ser uma URL"

        if erros: #Gerado a exeção que inclui todos os erros
            raise ValidationError(erros)

class Evento(models.Model):
    nome = models.CharField(max_length=155,verbose_name="Nome")
    data = models.DateField(verbose_name="Data")
    local = models.CharField(max_length=200,verbose_name="Local")
    def __str__(self):
        return self.nome
    
    def get_total_inscritos(self):
        return Evento.objects.filter(id=self.id).aggregate(Count('atividades__participantes'))['atividades__participantes__count']
    
class Participante(models.Model):
    nome = models.CharField(max_length=150,verbose_name="Nome")
    telefone =  models.CharField(max_length=20,verbose_name="Telefone")
    user=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True,related_name='participante')
    foto=models.ImageField(upload_to='participantes/',blank=True,null=True,verbose_name="Foto")

    def __str__(self):
        return self.nome

class Atividade(models.Model):
    TIPOS=(('OF','Oficina'),
           ('PR','Palestra'),
           ('MI','Minicurso'))
    data = models.DateField(verbose_name="Data da Atividade")
    hora = models.TimeField(verbose_name="Hora da Atividade")
    local = models.CharField(max_length=255,verbose_name="Local")
    titulo = models.CharField(max_length=255,verbose_name="Título")
    capacidade = models.IntegerField(verbose_name="Capacidade")
    ministrante = models.ForeignKey(Ministrante, on_delete=models.SET_NULL,verbose_name="Ministrante",related_name="atividades",null=True)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, related_name="atividades",verbose_name="Evento")
    participantes=models.ManyToManyField(Participante,through='Inscricao',related_name="atividades")
    tipo=models.CharField(max_length=20,choices=TIPOS,verbose_name="Tipos",default='OF')

    def get_capacidade_restante(self):
        return self.capacidade-self.participantes.count()
    
    def tem_vaga(self):
        return self.get_capacidade_restante()>0

    def __str__(self):
        return f'{self.evento}-{self.titulo}'

class Inscricao(models.Model):
    data = models.DateField(verbose_name="Data da Inscrição",auto_now_add=True)
    participante=models.ForeignKey(Participante,on_delete=models.CASCADE,verbose_name="Participante",related_name="inscricoes")
    atividade=models.ForeignKey(Atividade,on_delete=models.CASCADE,verbose_name="Atividade",related_name="inscricoes")
    presenca=models.BooleanField(verbose_name="Presença",default=False)

    def __str__(self):
        return f'{self.atividade}-{self.participante}'
    
    def save(self, *args, **kwargs):
        if self._state.adding:  # Verifica se é uma nova inscrição
            if not self.atividade.tem_vaga():
                raise ValidationError("Atividade com vagas esgotadas")
            if self.atividade.participantes.filter(id=self.participante.id).count() != 0:
                raise ValidationError("Participante já inscrito nessa atividade")
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural="Inscrições"

class Certificado(models.Model):
    data_emissao=models.DateField(verbose_name="Data do Certificado",auto_now_add=True)
    inscricao=models.OneToOneField(Inscricao,verbose_name="Inscrição",on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.inscricao}-{self.data_emissao}'
    def save(self, *args,**kwargs):
        if not self.inscricao.presenca:
            raise ValidationError("Não é possível gerar certificado para participante ausente")
        return super().save(*args,**kwargs)

class Avaliacao(models.Model):
    nota=models.IntegerField(verbose_name="Nota")
    comentario=models.TextField(verbose_name="Comentário")
    #Igual ao Foreign Key, on_delete é obrigatório
    inscricao=models.OneToOneField(Inscricao,verbose_name="Inscrição",on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.inscricao}'
    
    def save(self, *args, **kwargs):
        if not self.inscricao.presenca:
            raise ValidationError("Não é possível realizar avaliação para participante ausente")
        if self._state.adding:
            if Avaliacao.objects.filter(inscricao=self.inscricao).exists():
                raise ValidationError("Avaliação já registrada")
        return super().save(*args, **kwargs)
    class Meta:
        verbose_name_plural="Avaliações"

projeventos/appeventos/forms.py
from django import forms
from appeventos.models import Ministrante
class ContatoForm(forms.Form):
    assunto=forms.CharField()
    mensagem=forms.CharField(widget=forms.Textarea(attrs={'class':'textarea'}))
    remetente=forms.EmailField()

class MinistranteForm(forms.ModelForm):
    class Meta:
        model=Ministrante
        fields=['nome','data_nascimento','link_curriculo']

projeventos/appeventos/templates/appeventos/atividades/inscricoes.html
{% extends "appeventos/base.html" %}

{% block title %}Sistema de Eventos - Inscrições{% endblock %}

{% block conteudo %}
<div class="content">
    
    <h1>Deseja confirmar a Inscrição para a atividade {{atividade.titulo}}</h1>
      <form action="{% url 'appeventos:registrar_inscricao' atividade.id %}" method="post">
        {% csrf_token %}
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Salvar</button>
            </div>
            <div class="control">
              <a class="button is-text" href="{% url 'appeventos:index' %}">Cancelar</a>
            </div>
          </div>
      </form>
    
    
</div>
{% endblock %}
{% block footer %}
<p>
    <strong>TADS-CNAT</strong> Faça sua Inscrição!
</p>
{% endblock %}

projeventos/appeventos/templates/appeventos/atividades/inscritos.html
{% extends "appeventos/base.html" %}

{% block title %}Sistema de Eventos - Participantes{% endblock %}

{% block conteudo %}
<div class="content">
    
    <h1>Listagem de Participantes da Atividade {{atividade_titulo}}</h1>
    
    <form method="get" action="{% url 'appeventos:listar_participantes' atividade_id %}">
        <div class="field has-addons">
            <div class="control">
              <input class="input" type="text" name="criterio" value="{% if criterio %}{{criterio}}{% endif %}" placeholder="Buscar por nome">
            </div>
            <div class="control">
              <button class="button is-info">
                Buscar
              </button>
            </div>
          </div>
    </form>
<p></p>
    <form action="{% url 'appeventos:registrar_presenca' atividade_id%}" method="post">
        {% csrf_token %}
        <input type="hidden" name="criterio" value="{% if criterio %}{{criterio}}{% endif %}">
    <table class="table is-bordered is-striped is-hoverable is-narrow">
        <thead>
            <tr>
              <th>Nome</th>
              <th>Está Presente?</th>
            </tr>
          </thead>
          <tbody>
        {% for inscricao in inscricoes%}
            <tr>
                <td>{{inscricao.participante.nome}}</td>
                <td>
                    <input type="hidden" name="inscricoes_ids" value="{{inscricao.id}}">
                    <label class="checkbox">
                        <input type="checkbox" name="inscricao_{{inscricao.id}}" {% if inscricao.presenca %} checked {% endif %} />
                        Presente
                      </label>
                </td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
    <div class="control">
        <button class="button is-info">
          Salvar
        </button>
    </form>

    
    
</div>
{% endblock %}
{% block footer %}
<p>
    <strong>TADS-CNAT</strong> Listagem de Atividades
</p>
{% endblock %}

projeventos/appeventos/templates/appeventos/atividades/lista.html
{% extends "appeventos/base.html" %}

{% block title %}Sistema de Eventos - Atividades{% endblock %}

{% block conteudo %}
<div class="content">
    
    <h1>Listagem de Atividades do Evento {{nome_evento}}</h1>
    
    <form method="get" action="{% url 'appeventos:listar_atividades' evento_id %}">
        <div class="field has-addons">
            <div class="control">
              <input class="input" type="text" name="criterio" value="{% if criterio %} {{criterio}} {% endif %}" placeholder="Buscar pelo título">
            </div>
            <div class="control">
              <button class="button is-info">
                Buscar
              </button>
            </div>
          </div>
    </form>
<p></p>
    
    
    
    <table class="table is-bordered is-striped is-hoverable is-narrow">
        <thead>
            <tr>
              <th>Atividade</th>
              <th>Tipo</th>
              <th>Ministrante</th>
              <th>Data</th>
              <th>Hora</th>
              <th>Capacidade</th>
              <th>Vagas Disponíveis</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
        {% for atividade in page_obj %}
            <tr>
                {% if user.is_authenticated and user.is_superuser %}
                  <td><a href="{% url 'appeventos:listar_participantes' atividade.id %}">{{atividade.titulo|upper}}</a></td>
                {% else %}
                  <td>{{atividade.titulo|upper}}</td>
                {% endif %}
                <td>{{atividade.get_tipo_display}}</td>
                <td>{{atividade.ministrante.nome|upper}}</td>
                <td>{{atividade.data|date:"d/m/Y"}}</td>
                <td>{{atividade.hora|date:"H:i"}}</td>
                <td>{{atividade.capacidade}}</td>
                <td>{{atividade.get_capacidade_restante}}</td>
                {% if atividade.tem_vaga and user.participante %}
                    <td> <a href="{% url 'appeventos:exibir_form_inscricao' atividade.id%}" class="button is-link">Inscrição</a></td>
                {% else %}
                    {% if user.participante %}
                      <td> <span class="tag is-danger">Sem Vagas</span></td>
                    {% else %}
                      <td>-</td>
                    {% endif %}
                {% endif %}
                {% if user.participante %}
                <td> <a href="{% url 'appeventos:avaliar_atividade' atividade.id%}" class="button is-primary">Avaliar</span></td>
              {% else %}
                <td>-</td>
              {% endif %}
            </tr>
        {% endfor %}
    </tbody>
    </table>
    
</div>
{% endblock %}
{% block footer %}
<p>
    <strong>TADS-CNAT</strong> Listagem de Atividades
</p>
{% endblock %}

projeventos/appeventos/templates/appeventos/atividades/lista_participantes.html
{% extends "appeventos/base.html" %}

{% block title %}Sistema de Eventos - Participantes{% endblock %}

{% block conteudo %}
<div class="content">
    
    <h1>Listagem de Participantes da Atividade {{atividade_titulo}}</h1>
    
    <form method="get" action="{% url 'appeventos:listar_participantes' atividade_id %}">
        <div class="field has-addons">
            <div class="control">
              <input class="input" type="text" name="criterio" placeholder="Buscar por nome">
            </div>
            <div class="control">
              <button class="button is-info">
                Buscar
              </button>
            </div>
          </div>
    </form>
<p></p>
    <table class="table is-bordered is-striped is-hoverable is-narrow">
        <thead>
            <tr>
              <th>Nome</th>
            </tr>
          </thead>
          <tbody>
        {% for participante in participantes %}
            <tr>
                <td>{{participante.nome}}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>

    
    
</div>
{% endblock %}
{% block footer %}
<p>
    <strong>TADS-CNAT</strong> Listagem de Atividades
</p>
{% endblock %}