projeventos/appeventos/urls.py
from django.urls import path
#from .views import index,listar_eventos,listar_atividades,exibir_form_inscricao,registrar_inscricao,listar_participantes
from .views import EventoView,AtividadeView,AtividadeParticipanteView,InscricaoView,MinistranteListView,MinistranteCreateUpdateView,MinistranteDeleteView,ParticipanteCreateView,EventosLoginView,EventosLogoutView,AvalicaoCreateView,ToggleDarkModeView,FormContatoView,MinistranteFormCreateUpdateView
from django.views.generic import TemplateView
app_name='appeventos'
#urlpatterns=[
#    path('',index,name='index'),
#    path('eventos/listar',listar_eventos,name='listar_eventos'),
#    path('eventos/<int:evento_id>/atividades/listar',listar_atividades,name='listar_atividades'),
#    path('eventos/atividades/<int:atividade_id>/inscrever',exibir_form_inscricao,name='exibir_form_inscricao'),
#    path('eventos/atividades/<int:atividade_id>/registrar',registrar_inscricao,name="registrar_inscricao"),
#    path('eventos/atividades/<int:atividade_id>/participantes',listar_participantes,name='listar_participantes')
#]

urlpatterns=[
    path('',TemplateView.as_view(template_name='appeventos/index.html'),name='index'),
    path('eventos/listar',EventoView.as_view(),name='listar_eventos'),
    path('eventos/<int:evento_id>/atividades/listar',AtividadeView.as_view(),name='listar_atividades'),
    path('eventos/atividades/<int:atividade_id>/inscrever',InscricaoView.as_view(),name='exibir_form_inscricao'),
    path('eventos/atividades/<int:atividade_id>/registrar',InscricaoView.as_view(),name="registrar_inscricao"),
    path('eventos/atividades/<int:atividade_id>/participantes',AtividadeParticipanteView.as_view(),name='listar_participantes'),
    path('eventos/atividades/<int:atividade_id>/registrar_presenca',AtividadeParticipanteView.as_view(),name='registrar_presenca'),
    path('eventos/atividades/<int:atividade_id>/avaliar',AvalicaoCreateView.as_view(),name='avaliar_atividade'),
    path('ministrantes',MinistranteListView.as_view(),name='listar_ministrantes'),
    #path('ministrantes/cadastrar',MinistranteCreateUpdateView.as_view(),name='cadastrar_ministrante'),
    #path('ministrante/<int:ministrante_id>/editar',MinistranteCreateUpdateView.as_view(),name='editar_ministrante'),
    path('ministrantes/cadastrar',MinistranteFormCreateUpdateView.as_view(),name='cadastrar_ministrante'),
    path('ministrante/<int:ministrante_id>/editar',MinistranteFormCreateUpdateView.as_view(),name='editar_ministrante'),
    path('ministrante/<int:pk>/excluir',MinistranteDeleteView.as_view(),name='excluir_ministrante'),
    path('participantes/registrar',ParticipanteCreateView.as_view(),name='registrar_participante'),
    path('darkmode/',ToggleDarkModeView.as_view(),name='darkmode'),
    path('contato/',FormContatoView.as_view(),name='contato'),
    path('login/',EventosLoginView.as_view(),name='login'),
    path('logout/',EventosLogoutView.as_view(),name='logout'),
    ]

projeventos/projeventos/urls.py
from django.contrib import admin
from django.urls import path,include,reverse
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("appeventos/",include("appeventos.urls")),
     path("",RedirectView.as_view(url="appeventos/")),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projeventos/appeventos/forms.py
from django import forms
from appeventos.models import Ministrante
class ContatoForm(forms.Form):
    assunto=forms.CharField()
    mensagem=forms.CharField(widget=forms.Textarea(attrs={'class':'textarea'}))
    remetente=forms.EmailField()

class MinistranteForm(forms.ModelForm):
    class Meta:
        model=Ministrante
        fields=['nome','data_nascimento','link_curriculo']

projeventos/appeventos/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import View
from django.urls import reverse_lazy
from django.core.exceptions import ValidationError,ObjectDoesNotExist
from django.views.generic import ListView,DeleteView
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from appeventos.models import Atividade,Evento,Inscricao,Participante,Ministrante,Avaliacao
from appeventos.forms import ContatoForm,MinistranteForm
import os

def eh_participante(user):
    return hasattr(user,'participante')

def eh_administrador(user):
    return user.is_superuser

class EventoView(ListView):
    model=Evento
    paginate_by=2
    context_object_name="eventos"
    queryset=Evento.objects.order_by("-data")
    template_name="appeventos/eventos/lista.html"

class AtividadeView(View):
    template='appeventos/atividades/lista.html'
    def get(self,request,evento_id):
        evento=get_object_or_404(Evento,pk=evento_id)
        criterio=request.GET.get('criterio')
        if criterio==None:
            atividades=Atividade.objects.filter(evento=evento).order_by('-data','hora')
        else:
            atividades=Atividade.objects.filter(evento=evento,titulo__icontains=criterio).order_by('-data','hora')
        if atividades.count()==0:
            messages.error(request=request,message="Evento sem Atividades ou Nenhuma atividade encontrada com o critério informado")
            context={'nome_evento':evento.nome,'evento_id':evento.id,'criterio':criterio}
            return render(request,template_name=self.template,context=context)
        else:
            paginator=Paginator(atividades,2)
            page_number=request.GET.get("page")
            page_obj=paginator.get_page(page_number)
            context={'atividades':atividades,'nome_evento':evento.nome,'criterio':criterio,'evento_id':evento.id,'page_obj':page_obj,'is_paginated':True}
            return render(request,template_name=self.template,context=context)

@method_decorator(user_passes_test(eh_administrador),name='dispatch')
class AtividadeParticipanteView(LoginRequiredMixin,View):
    def get(self,request,atividade_id):
        criterio=request.GET.get('criterio')
        context=self.buscaInscricoes(criterio,atividade_id)
        return render(request,template_name='appeventos/atividades/inscritos.html',context=context)
    def post(self,request,atividade_id):
        atividade=get_object_or_404(Atividade,pk=atividade_id)
        inscricoes_ids=request.POST.getlist("inscricoes_ids")
        for inscricao_id in inscricoes_ids:
            marcado=f'inscricao_{inscricao_id}' in request.POST
            Inscricao.objects.filter(id=inscricao_id).update(presenca=marcado)
        messages.success(request=request,message="Presenças Registradas com Sucesso!")
        context=self.buscaInscricoes(request.POST.get('criterio'),atividade_id)
        return render(request,template_name='appeventos/atividades/inscritos.html',context=context)
    
    def buscaInscricoes(self, criterio,atividade_id):
        atividade=get_object_or_404(Atividade,pk=atividade_id)
        if criterio==None:
            inscricoes=Inscricao.objects.filter(atividade=atividade).order_by("participante__nome")
        else:
            inscricoes=Inscricao.objects.filter(atividade=atividade,participante__nome__icontains=criterio).order_by("participante__nome")
        context={
            'atividade_id':atividade.id,
            'atividade_titulo':atividade.titulo,
            'inscricoes':inscricoes,
            'criterio':criterio
        }
        return context

@method_decorator(user_passes_test(eh_participante),name='dispatch')
class InscricaoView(LoginRequiredMixin,View):
    template_name='appeventos/atividades/inscricoes.html'
    def get(self,request,atividade_id):
        atividade=get_object_or_404(Atividade,pk=atividade_id)
        context={'atividade':atividade}
        return render(request,template_name=self.template_name,context=context)
    def post(self,request,atividade_id):
        atividade=get_object_or_404(Atividade,pk=atividade_id)
        participante=request.user.participante
        try:
            inscricao=Inscricao(atividade=atividade,participante=participante)
            inscricao.save()
            messages.success(request,message='Inscrição realizada com sucesso')
            return redirect("appeventos:listar_atividades",evento_id=atividade.evento.id)
        except ValidationError as error:
            messages.error(request,message=error.message)
            return redirect('appeventos:listar_atividades',evento_id=atividade.evento.id)

@method_decorator(user_passes_test(eh_administrador),name='dispatch')
class MinistranteListView(ListView,LoginRequiredMixin):
    model=Ministrante
    context_object_name="ministrantes"
    template_name="appeventos/ministrantes/lista.html"
    paginate_by=3



    def get_queryset(self):
        queryset=Ministrante.objects.order_by("nome")
        criterio=self.request.GET.get("criterio")
        if criterio:
            queryset=queryset.filter(nome__icontains=criterio).order_by("nome")
        return queryset

@method_decorator(user_passes_test(eh_administrador),name='dispatch')
class MinistranteCreateUpdateView(View,LoginRequiredMixin):
    template_name="appeventos/ministrantes/form.html"
    def get(self,request,*args,**kwargs):
        ministrante_id=kwargs.get("ministrante_id")
        if ministrante_id:
            ministrante=get_object_or_404(Ministrante,pk=ministrante_id)
        else:
            ministrante=None
        context={"ministrante":ministrante}
        return render(request=request,template_name=self.template_name,context=context)
    
    def post(self,request,*args,**kwargs):
        ministrante_id=kwargs.get("ministrante_id")
        nome=request.POST.get('nome')
        data_nascimento=request.POST.get('data_nascimento')
        link_curriculo=request.POST.get('link_curriculo')
        if ministrante_id:
            ministrante=get_object_or_404(Ministrante,pk=ministrante_id)
            ministrante.nome=nome
            ministrante.data_nascimento=data_nascimento
            ministrante.link_curriculo=link_curriculo
        else:
            ministrante=Ministrante(nome=nome,data_nascimento=data_nascimento,link_curriculo=link_curriculo)
        try:
            ministrante.full_clean()
            ministrante.save()
            messages.success(request=request,message=f"Ministrante {ministrante.nome} Salvo com Sucesso")
            return redirect("appeventos:listar_ministrantes")
        except ValidationError as error:
            for atributo, error_list in error.message_dict.items():
                for error in error_list:
                    messages.error(request=request,message=f"{error}")
            context={'ministrante':ministrante}
            return render(request=request,template_name=self.template_name,context=context)

@method_decorator(user_passes_test(eh_administrador),name='dispatch')
class MinistranteDeleteView(DeleteView,LoginRequiredMixin):
    model=Ministrante
    template_name="appeventos/ministrantes/excluir.html"
    success_url=reverse_lazy("appeventos:listar_ministrantes")
class MinistranteDeleteView(DeleteView):
    model=Ministrante
    template_name="appeventos/ministrantes/excluir.html"
    #https://docs.djangoproject.com/en/5.1/ref/urlresolvers/#reverse-lazy
    success_url=reverse_lazy("appeventos:listar_ministrantes")

class EventosLoginView(LoginView):
    template_name = 'appeventos/login.html'
    
    def form_invalid(self, form):
        # Exibe mensagem de erro para credenciais inválidas
        messages.error(self.request, "Credenciais inválidas. Por favor, verifique seu usuário e senha.")
        return super().form_invalid(form)


class EventosLogoutView(LogoutView):
    http_method_names=['get','post']

    def get(self, request, *args, **kwargs):
        # Adiciona a mensagem de sucesso para o logout via GET
        logout(request)
        messages.success(request, "Você foi desconectado com sucesso.")
        return redirect('appeventos:index')

    def post(self, request, *args, **kwargs):
        # Caso você queira tratar o POST também
        logout(request)
        messages.success(request, "Você foi desconectado com sucesso.")
        return redirect('appeventos:index')

ALLOWED_EXTENSIONS = ['.png', '.jpg', '.jpeg']

class ParticipanteCreateView(View):
    template_name="appeventos/participantes/form.html"
    def get(self,request):
        if request.user.is_authenticated:
            print(request.user)
            return redirect("appeventos:index")
        else:
            return render(request=request,template_name=self.template_name)
    def post(self,request):
        login=request.POST.get("login")
        nome=request.POST.get("nome")
        senha=request.POST.get("senha")
        email=request.POST.get("email")
        telefone=request.POST.get("telefone")
        foto=request.FILES.get('foto')
        if User.objects.filter(username=login).exists():
            messages.error(request,"Login já existente. Por favor, escolha outro")
            return render(request,self.template_name)
        if foto:
            ext = os.path.splitext(foto.name)[1].lower()  # Obtém a extensão, ex: '.jpg'
            if ext not in ALLOWED_EXTENSIONS:
                messages.error(request, "Tipo de arquivo inválido. Envie apenas imagens PNG ou JPG.")
                return render(request, self.template_name)
        
        #Cria o usuário Django

        user=User.objects.create_user(username=login,password=senha,email=email)

projeventos/appeventos/templates/appeventos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sistema de Eventos{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma/css/bulma.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'appeventos/css/darkmode.css' %}">
</head>
<body class="{% if request.session.dark_mode %}dark-mode{% endif %}">
    <nav class="navbar is-primary">
        <div class="navbar-start">
            <a class="navbar-item" href="{% url 'appeventos:index' %}">Sistema de Eventos</a>
            <a class="navbar-item" href="{% url 'appeventos:listar_eventos' %}">Eventos</a>
            {% if user.is_superuser %}
                <a class="navbar-item" href="{% url 'appeventos:listar_ministrantes' %}">Ministrantes</a>
            {%endif%}
            <a class="navbar-item" href="{% url 'admin:index' %}">Administrador</a>
            <a class="navbar-item" href="{% url 'appeventos:contato' %}">Contato</a>
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <button id="dark-mode-toggle" class="button is-light">{% if request.session.dark_mode %}Modo Claro{% else %}Modo Escuro{% endif %}</button>
            </div>
            {% if user.is_authenticated %}
            <div class="navbar-item">
                <figure class="image is-32x32">
                  <img class="is-rounded" src="{% if user.is_superuser %} {% static 'appeventos/img/default-user.jpg' %} {% else %} {{ user.participante.foto.url }} {% endif %}" alt="Foto do usuário">
                </figure>
                <span>{% if user.is_superuser %} {{user.username}} {% else %} {{ user.participante.nome}} {% endif %}</span>
              </div>
              <div class="navbar-item">
                <div class="buttons">
                  <a class="button is-light" href="{% url 'appeventos:logout' %}">
                    Logout
                  </a>
                </div>
              </div>
            {%else%}
            <div class="navbar-item">
                <div class="buttons">
                  <a class="button is-primary" href="{% url 'appeventos:registrar_participante'%}">
                    <strong>Registre-se</strong>
                  </a>
                  <a class="button is-light" href="{% url 'appeventos:login'%}">
                    Login
                  </a>
                </div>
              </div>
            </div>
            {%endif%}
            
    </nav>
    {% block mensagens %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="notification is-danger">
                    <button class="delete"></button>
                    <strong>Erro: </strong> {{message}}
                </div>
            {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="notification is-info">
                <button class="delete"></button>
                <strong>Sucesso: </strong> {{message}}
            </div>
            {% endif %}
        {% endfor %}

    {% endblock %}
    <section class="section">
        <div class="container">
            {% block conteudo %}{% endblock %}
        </div>
    </section>
    {% block pagination %}
    {% if is_paginated %}
        <nav class="pagination" role="navigation" aria-label="pagination">
                {% if page_obj.has_previous %}
                    <a class="pagination-previous" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}
                <ul class="pagination-list">
                    <li><a class="pagination-link is-current" href="?page={{page_obj.number}}">{{page_obj.number}}</a></li>
                </ul>
                {% if page_obj.has_next %}
                    <a class="pagination-next" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Próximo</a>
                {% endif %}
            </nav>
    {% endif %}
  {% endblock %}

    <footer class="footer">
        <div class="content has-text-centered">
            {%block footer %}{% endblock %}
        </div>
    </footer>

        ...
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const toggleButton = document.getElementById('dark-mode-toggle');
            const body = document.body;
    
            toggleButton.addEventListener('click', () => {
                fetch("{% url 'appeventos:darkmode' %}")
                .then(response => response.json())
                .then(data => {
                    if (data.dark_mode) {
                        body.classList.add('dark-mode');
                        toggleButton.textContent = 'Modo Claro';
                    } else {
                        body.classList.remove('dark-mode');
                        toggleButton.textContent = 'Modo Escuro';
                    }
                });
            });
        });
    </script>
    </body>
    </html>

</body>
</html>

projeventos/appeventos/templates/appeventos/index.html
{% extends "appeventos/base.html" %}

{% block title %}Sistema de Eventos{% endblock %}
{% block conteudo %}
<div class="content">
    <h1>Sistema de Gerenciamento de Eventos</h1>
  <p>
    Lorem ipsum<sup><a>[1]</a></sup> dolor sit amet, consectetur adipiscing
    elit. Nulla accumsan, metus ultrices eleifend gravida, nulla nunc varius
    lectus, nec rutrum justo nibh eu lectus. Ut vulputate semper dui. Fusce erat
    odio, sollicitudin vel erat vel, interdum mattis neque. Sub<sub>script</sub>
    works as well!
  </p>
</div>
{% endblock %}
{% block footer %}
<p>
    <strong>TADS-CNAT</strong> Página Inicial do Sistema de Gerenciamento de Eventos
  </p>
{% endblock %}

projeventos/appeventos/templates/appeventos/login.html
{% extends 'appeventos/base.html' %}
{% block title %}Sistema de Gerenciamento de Eventos - Login{% endblock %}
{% block conteudo %}
  <div class="column is-4 is-offset-4">
    <h1 class="title has-text-centered">Login</h1>
    <form method="post">
      {% csrf_token %}
      <div class="field">
        <label class="label" for="id_username">Usuário</label>
        <div class="control">
          <input class="input" type="text" name="username" id="id_username" required>
        </div>
      </div>
      <div class="field">
        <label class="label" for="id_password">Senha</label>
        <div class="control">
          <input class="input" type="password" name="password" id="id_password" required>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <button class="button is-primary is-fullwidth" type="submit">Entrar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}