projpolls/polls/urls.py
from django.urls import path
from . import views
app_name='polls' #Código adicionado
urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.DetailView.as_view(),name='details'),
    path('<int:pk>/results/',views.ResultsView.as_view(),name='results'),
    path('<int:pk>/alternativa/',views.AlternativaView.as_view(),name='alternativas'),
    path('<int:question_id>/alternativa/cadastrar',views.cadastrar_alternativa,name='cadastrar_alternativa'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
]

projpolls/projpolls/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/",include('polls.urls')),
]

projpolls/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
class Question(models.Model):
    question_text=models.CharField(max_length=200,verbose_name="Texto da Questão")
    pub_date=models.DateTimeField(verbose_name="Data da Publicação")
    def __str__(self):
        return self.question_text
    def foi_publicado_recentemente(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200,verbose_name="Alternativa")
    votes=models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_text

projpolls/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Question,Choice

# Create your views here.
'''
def index(request):
    #- indica que ele vai colocar em ordem decrescente
    lista_questoes=Question.objects.all()
    context={'lista':lista_questoes}
    return render(request,'index.html',context)
def details(request,question_id):
    questao=get_object_or_404(Question,pk=question_id)
    context={'questao':questao}
    return render(request,'details.html',context)
def results(request,question_id):
    questao=get_object_or_404(Question,pk=question_id)
    context={'questao':questao}
    return render(request,'results.html',context)
'''

def vote(request,question_id):
    questao=get_object_or_404(Question,pk=question_id)
    try:
        alternativa=questao.choice_set.get(pk=request.POST['alternativa'])
    except(KeyError,Choice.DoesNotExist):
        context={'questao':questao,'mensagem_erro':'Você não selecionou uma alternativa'}
        return render(request,'details.html',context)
    else:
        alternativa.votes+=1
        alternativa.save()
        return HttpResponseRedirect(reverse('polls:results',args=(question_id,)))

def cadastrar_alternativa(request,question_id):
    questao=get_object_or_404(Question,pk=question_id)
    texto_alternativa=request.POST['alternativa']
    if len(texto_alternativa)==0:
        context={'questao':questao,'mensagem_erro':'Você não preencheu a alternativa'}
        return render(request,'form_alternativa.html',context)
    else:
        alternativa=Choice(question=questao,
                           choice_text=texto_alternativa)
        alternativa.save()
        return HttpResponseRedirect(reverse('polls:index'))

class IndexView(generic.ListView):
    context_object_name="lista"
    model=Question
    template_name='index.html'

class AlternativaView(generic.DetailView):
    model=Question
    context_object_name='questao'
    template_name='form_alternativa.html'

class DetailView(generic.DetailView):
    model=Question
    context_object_name='questao'
    template_name='details.html'

class ResultsView(generic.DetailView):
    model=Question
    context_object_name='questao'
    template_name='results.html'

projpolls/polls/templates/details.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Enquetes</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    {%load static%}

    <link rel="stylesheet" href="{% static 'polls/css/style.css'%}">
</head>
<body>
    <h1 class="title">{{questao.question_text}}</h1>
        {% if mensagem_erro %}
        <p class="notification is-danger">{{mensagem_erro}}</p>
        {% endif %}
            {% if questao.choice_set.count > 0 %}
                <form action="{% url 'polls:vote' questao.id %}" method="post">
                    {% csrf_token %}
                {% for choice in questao.choice_set.all %}
                    <div>
                        <label class="radio">
                        <input type="radio" name="alternativa" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
                        {{choice.choice_text}}
                        </label>
                    </div>
                {% endfor %}
                <p><button class="button is-link">Votar</button></p>
                </form>
            {% else %}
                    <div class="notification is-danger">Questão sem alternativas cadastradas</div>
            {% endif %}      
    </body>
</body>
</html>

projpolls/polls/templates/form_alternativa.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Enquetes</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
</head>
<body>
    <h1 class="title">{{questao.question_text}}</h1>
        {% if mensagem_erro %}
        <p class="notification is-danger">{{mensagem_erro}}</p>
        {% endif %}
                <form action="{% url 'polls:cadastrar_alternativa' questao.id %}" method="post">
                    {% csrf_token %}
                    <div class="field">
                        <label class="label">Alternativa:</label>
                        <div class="control">
                          <input class="input" type="text" placeholder="alternativa" name="alternativa">
                        </div>
                      </div>
                      
                <p><button class="button is-link">Cadastrar</button></p>
                </form>     
    </body>
</body>
</html>

projpolls/polls/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Enquetes</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    {%load static%}
    <link rel="stylesheet" href="{% static 'polls/css/style.css'%}">
</head>
<body>
    <h1 class="title">Enquetes</h1>
        <ul>
        {% if lista %}
            {% for questao in lista %}
                <li>
                        <a class="button is-primary" href="{% url 'polls:details' questao.id %}">Questão: {{ questao.question_text }}</a>
                        <a class="button is-info" href="{% url 'polls:results' questao.id %}">Resultado</a>
                        <a class="button is-light" href="{% url 'polls:alternativas' questao.id %}">Cadastrar Alternativa</a>
                    </li>
            {% endfor %}
        {% else %}
                <p class="notification is-danger">Nenhuma Questão Disponível</p>
        {% endif %}
    </ul>       
    </body>
</body>
</html>

projpolls/polls/templates/results.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Enquetes</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    {%load static%}

    <link rel="stylesheet" href="{% static 'polls/css/style.css'%}">
</head>
<body>
    <h1 class="title">{{questao.question_text}}</h1>

            {% if questao.choice_set.count > 0%}
            <table class="table is-bordered is-hoverable is-narrow">
                <thead>
                    <tr>
                      <th>Alternativa</th>
                      <th>Votos</th>
                    </tr>
                  </thead>
                  <tbody>
                {% for choice in questao.choice_set.all %}
                    <tr>
                        <td>{{choice.choice_text}}</td>
                        <td>{{choice.votes}}</td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
            {% else %}
                    <p class="notification is-danger">Questão sem alternativas cadastradas</p>
            {%endif%}  
            
            <a class="button is-primary" href="{% url 'polls:index' %}">Voltar</a>
    </body>
</body>
</html>